server:
  port: 6001

#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
        zuul:
          routes:
            my-route: # 标识 代表一组 路由名称 随便起一个就好了 没有任何意义,如果没有配置 和service-id是一样的
              service-id: microservice-order-consumer # 微服务的名字 要被路由的微服务
              path: /zuuls/** # url地址