server:
  port: 2000
spring:
  application:
    name: microservice-order-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # 设置拉取服务的间隔时间5秒
  instance:
    prefer-ip-address: true  # 将IP注册到Eureka Server上，如果不配置就是机器的主机名
    lease-renewal-interval-in-seconds: 5  # 心跳时间：5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 过期时间：15秒不发送就过期

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:6000 # 设置hystrix的超时时间为6000ms

feign:
  hystrix:
    enabled: true # 开启hystrix熔断器

